FROM node:latest

RUN npm install -g typescript
RUN npm install -g ts-node

ARG PORT=3500
ARG FRONTEND_URL
ARG BACKEND_URL
ARG APP_SECRET
ARG DATABASE_NAME
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG DATABASE_HOST
ARG DATABASE_DIALECT
ARG S3_ACCESS_KEY
ARG S3_SECRET_ACCESS_KEY
ARG S3_BUCKET_NAME
ARG S3_REGION
ARG AWS_S3_URL
ENV PORT=${PORT} \
    FRONTEND_URL=${FRONTEND_URL} \
    BACKEND_URL=${BACKEND_URL} \
    APP_SECRET=${APP_SECRET} \
    DATABASE_NAME=${DATABASE_NAME} \
    DATABASE_USERNAME=${DATABASE_USERNAME} \
    DATABASE_PASSWORD=${DATABASE_PASSWORD} \
    DATABASE_HOST=${DATABASE_HOST} \
    DATABASE_DIALECT=${DATABASE_DIALECT} \
    S3_ACCESS_KEY=${S3_ACCESS_KEY} \
    S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY} \
    S3_BUCKET_NAME=${S3_BUCKET_NAME} \
    S3_REGION=${S3_REGION} \
    AWS_S3_URL=${AWS_S3_URL}

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

EXPOSE $PORT

CMD [ "npm","run","start:prod" ]