import { Response } from "express";
import constants from "../../helpers/constants";
import { RequestWithUser } from "../../interfaces/common.interface";
import { IUser } from "../../interfaces/user.interface";
import { groupSchema } from "../../validation/wms/gm.validation";
import { GroupService } from "../../services/WMS/group.service";

export const createGroup = async (req: RequestWithUser, res: Response) => {
  try {
    const requestUser: IUser = req.user;

    const { error } = groupSchema(req.body);
    if (error) {
      res
        .status(constants.STATUS_CODES.BAD_REQUEST)
        .json({ success: false, message: error.message });
      return;
    }
    const {
      company_code,
      prin_code,
      group_name,
      pref_site,
      pref_loc_from,
      pref_loc_to,
      pref_aisle_from,
      pref_aisle_to,
      pref_col_from,
      pref_col_to,
      pref_ht_from,
      pref_ht_to,
      expiry_cons_days,
    } = req.body;

    // Create new group using service (group_code will be generated by DB trigger)
    const createGroup = await GroupService.createGroup({
      prinCode: prin_code,
      companyCode: company_code,
      groupName: group_name,
      prefSite: pref_site,
      prefLocFrom: pref_loc_from,
      prefLocTo: pref_loc_to,
      prefAisleFrom: pref_aisle_from,
      prefAisleTo: pref_aisle_to,
      prefColFrom: pref_col_from,
      prefColTo: pref_col_to,
      prefHtFrom: pref_ht_from,
      prefHtTo: pref_ht_to,
      expiryConsDays: expiry_cons_days,
      createdBy: requestUser.loginid,
      updatedBy: requestUser.loginid,
    } as any);

    if (!createGroup) {
      res
        .status(constants.STATUS_CODES.INTERNAL_SERVER_ERROR)
        .json({ success: false, message: "Error while creating group" });
      return;
    }
    res.status(constants.STATUS_CODES.OK).json({
      success: true,
      message: constants.MESSAGES.GROUP_WMS.GROUP_CREATED_SUCCESSFULLY,
    });
    return;
  } catch (error: any) {
    res
      .status(constants.STATUS_CODES.BAD_REQUEST)
      .json({ success: false, message: error.message });
    return;
  }
};

export const updateGroup = async (req: RequestWithUser, res: Response) => {
  try {
    const requestUser: IUser = req.user;

    const { error } = groupSchema(req.body);
    if (error) {
      res
        .status(constants.STATUS_CODES.BAD_REQUEST)
        .json({ success: false, message: error.message });
      return;
    } const {
      group_code,
      company_code,
      prin_code,
      group_name,
      pref_site,           // This was missing
      pref_loc_from,       // This was missing
      pref_loc_to,         // This was missing
      pref_aisle_from,     // This was missing
      pref_aisle_to,       // This was missing
      pref_col_from,       // This was missing
      pref_col_to,         // This was missing
      pref_ht_from,        // This was missing
      pref_ht_to,          // This was missing
      expiry_cons_days,    // This was missing
    } = req.body;

    // Check if group exists
    const groupExists = await GroupService.findByGroupCodeAndCompany(
      group_code,
      prin_code,
      company_code
    );

    if (!groupExists) {
      res.status(constants.STATUS_CODES.BAD_REQUEST).json({
        success: false,
        message: constants.MESSAGES.GROUP_WMS.GROUP_DOES_NOT_EXISTS,
      });
      return;
    }

    // Update group using service
    const updateSuccess = await GroupService.updateGroup(
      group_code,
      prin_code,
      company_code,
      {
        groupName: group_name,
        prefSite: pref_site,
        prefLocFrom: pref_loc_from,
        prefLocTo: pref_loc_to,
        prefAisleFrom: pref_aisle_from,
        prefAisleTo: pref_aisle_to,
        prefColFrom: pref_col_from,
        prefColTo: pref_col_to,
        prefHtFrom: pref_ht_from,
        prefHtTo: pref_ht_to,
        expiryConsDays: expiry_cons_days,
        updatedBy: requestUser.loginid,
      }
    );

    if (!updateSuccess) {
      res
        .status(constants.STATUS_CODES.INTERNAL_SERVER_ERROR)
        .json({ success: false, message: "Error while updating group" });
      return;
    }
    res.status(constants.STATUS_CODES.OK).json({
      success: true,
      message: constants.MESSAGES.GROUP_WMS.GROUP_UPDATED_SUCCESSFULLY,
    });
    return;
  } catch (error: any) {
    res
      .status(constants.STATUS_CODES.BAD_REQUEST)
      .json({ success: false, message: error.message });
    return;
  }
};

export const deleteCountries = async (req: RequestWithUser, res: Response) => {
  try {
    const groupsToDelete = req.body;

    if (!Array.isArray(groupsToDelete) || !groupsToDelete.length) {
      res.status(constants.STATUS_CODES.BAD_REQUEST).json({
        success: false,
        message: constants.MESSAGES.GROUP_WMS.SELECT_AT_LEAST_ONE_GROUP,
      });
      return;
    }

    // Expecting array of objects with group_code, prin_code, company_code
    // For simplicity, assume all have same prin_code and company_code
    const groupCodes = groupsToDelete.map((g: any) => g.group_code);
    const prinCode = groupsToDelete[0]?.prin_code;
    const companyCode = groupsToDelete[0]?.company_code;

    const deleteSuccess = await GroupService.deleteGroups(
      groupCodes,
      prinCode,
      companyCode
    );

    if (!deleteSuccess) {
      res.status(constants.STATUS_CODES.BAD_REQUEST).json({
        success: false,
        message: "Failed to delete groups",
      });
      return;
    }
    res.status(constants.STATUS_CODES.OK).json({
      success: true,
      message: constants.MESSAGES.GROUP_WMS.GROUP_DELETED_SUCCESSFULLY,
    });
    return;
  } catch (error: any) {
    res
      .status(constants.STATUS_CODES.BAD_REQUEST)
      .json({ success: false, message: error.message });
    return;
  }
};
   